### PR TITLE
Add autoplay, autoplayMode and playinline to CldVideoPlayer

### PR DESCRIPTION
**Pull request by Marcos-Bernasconi**
# Summary:
Autoplay seemed to not work correctly because some props were missing. Adding autoPlay, playsinline and autoPlayMode as props resolved the problem
  
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
I added the followings props to CldVideoPlayer:
- autoPlay?: boolean
- autoplayMode?: "never" | "always" | "on-scroll";
- playsinline?: boolean; (needed for iOS devices to autoplay videos)

I changed autoplayMode from a string to a union of the [possible values](https://cloudinary.com/documentation/video_player_api_reference#autoplaymode).
Made also autoplayMode default value `always` so videos autoPlay correctly just by passing autoPlay = true.

Resolves:#242

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Marcos-Bernasconi** [comment]
It seems that my prettier formatting was a bit different and unintentionally added colons and double quotes :/
I am so happy, this is my first pull request!

**Comment by Baroshem** [comment]
Hey there,

Thanks for this amazing work! You did a great job.
About linting. Could you run `pnpm run lint` in your project and then commit the changes? It should help :)

**Comment by Marcos-Bernasconi** [comment]
Hi Baroshem, thank you again! :)
I tried also to update the docs to reflect the changes.

**Comment by Baroshem** [comment]
Hey Buddy, thank you for this change!

I will merge it to 4.0.0 branch and release a bigger major version at the start of next month (after all the goodies from hacktoberfest :) )

**Pull request merged**
